name: test win32 with MSVC

on:
  push:
    branches: [ mob ]

jobs:
  test-i386-win32:
    runs-on: windows-2025
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4
    - name: test (i386-win32)
      shell: cmd
      run: |
        echo ::group:: run build-tcc.bat
        cd win32
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x86
        call build-tcc.bat -c cl -t i386
        echo off
        echo ::endgroup::
        set ARCH=i386
        set CC=gcc
        set PATH=c:\mingw32\bin;%PATH%
        echo>>..\config.h #define CC_NAME CC_%CC%
        echo>..\config.mak # -----------
        echo>>..\config.mak prefix = .
        echo>>..\config.mak CC = %CC%.exe
        echo>>..\config.mak CC_NAME = %CC%
        echo>>..\config.mak GCC_MAJOR = 15
        echo>>..\config.mak CFLAGS = -O0
        echo>>..\config.mak LDFLAGS =
        echo>>..\config.mak LIBSUF = .lib
        echo>>..\config.mak EXESUF = .exe
        echo>>..\config.mak DLLSUF = .dll
        echo>>..\config.mak ARCH = %ARCH%
        echo>>..\config.mak TARGETOS = WIN32
        echo>>..\config.mak CONFIG_WIN32 = yes
        echo>>..\config.mak VERSION = 0.9.28rc
        echo>>..\config.mak TOPSRC = $(TOP)
        echo>>..\config.mak TESTREF_FLAGS = crt.c -nostdlib -Wl,-entry=_start -lgcc -lkernel32
        echo>>..\config.mak SHELL = sh
        set PATH=%CD%;%PATH%
        cd ..\tests
        make test -k TCC_LOCAL=tcc.exe LIBTCC=win32/libtcc.dll

  test-x86_64-win32:
    runs-on: windows-2025
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4
    - name: test (x86_64-win32)
      shell: cmd
      run: |
        echo ::group:: run build-tcc.bat
        cd win32
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64
        call build-tcc.bat -c cl -t x86_64
        echo off
        echo ::endgroup::
        set ARCH=x86_64
        set CC=gcc
        echo>>..\config.h #define CC_NAME CC_%CC%
        echo>..\config.mak # -----------
        echo>>..\config.mak prefix = .
        echo>>..\config.mak CC = %CC%.exe
        echo>>..\config.mak CC_NAME = %CC%
        echo>>..\config.mak GCC_MAJOR = 15
        echo>>..\config.mak CFLAGS = -O0
        echo>>..\config.mak LDFLAGS =
        echo>>..\config.mak LIBSUF = .lib
        echo>>..\config.mak EXESUF = .exe
        echo>>..\config.mak DLLSUF = .dll
        echo>>..\config.mak ARCH = %ARCH%
        echo>>..\config.mak TARGETOS = WIN32
        echo>>..\config.mak CONFIG_WIN32 = yes
        echo>>..\config.mak VERSION = 0.9.28rc
        echo>>..\config.mak TOPSRC = $(TOP)
        echo>>..\config.mak TESTREF_FLAGS = crt.c -nostdlib -Wl,-entry=_start -lgcc -lkernel32
        echo>>..\config.mak SHELL = sh
        set PATH=%CD%;%PATH%
        cd ..\tests
        make test -k TCC_LOCAL=tcc.exe LIBTCC=win32/libtcc.dll

  test-arm64-win32:
    runs-on: windows-11-arm
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4
    - name: test (arm64-win32)
      shell: cmd
      run: |
        echo ::group:: run build-tcc.bat
        cd win32
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=arm64
        call build-tcc.bat -c cl -t arm64
        echo off
        echo ::endgroup::
        set ARCH=aarch64
        set CC=clang
        echo>>..\config.h #define CC_NAME CC_%CC%
        echo>..\config.mak # -----------
        echo>>..\config.mak prefix = .
        echo>>..\config.mak CC = %CC%.exe
        echo>>..\config.mak CC_NAME = %CC%
        echo>>..\config.mak GCC_MAJOR = 15
        echo>>..\config.mak CFLAGS = -O0
        echo>>..\config.mak LDFLAGS =
        echo>>..\config.mak LIBSUF = .lib
        echo>>..\config.mak EXESUF = .exe
        echo>>..\config.mak DLLSUF = .dll
        echo>>..\config.mak ARCH = %ARCH%
        echo>>..\config.mak TARGETOS = WIN32
        echo>>..\config.mak CONFIG_WIN32 = yes
        echo>>..\config.mak VERSION = 0.9.28rc
        echo>>..\config.mak TOPSRC = $(TOP)
        echo>>..\config.mak TESTREF_FLAGS = crt.c -nostdlib -lkernel32
        echo>>..\config.mak SHELL = sh
        set PATH=%CD%;%PATH%
        cd ..\tests
        make test -k TCC_LOCAL=tcc.exe LIBTCC=win32/libtcc.lib
