name: test win32 with MSVC

on:
  push:
    branches: [ arm64-win32 ]

  workflow_dispatch:

jobs:
  test-i386-win32:
    runs-on: windows-2025
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4
    - name: test (i386-win32)
      shell: cmd
      run: |
        echo ::group:: run build-tcc.bat
        cd win32
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x86
        call build-tcc.bat -c cl -t i386
        @echo off
        echo ::endgroup::
        cd ..\tests
        call test-win32.bat -c gcc -t i386 -p c:\mingw32\bin test -k

  test-x86_64-win32:
    runs-on: windows-2025
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4
    - name: test (x86_64-win32)
      shell: cmd
      run: |
        echo ::group:: run build-tcc.bat
        cd win32
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64
        call build-tcc.bat -c cl -t x86_64
        @echo off
        echo ::endgroup::
        cd ..\tests
        call test-win32.bat -c gcc -t x86_64 test -k

  test-arm64-win32:
    runs-on: windows-11-arm
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4
    - name: test (arm64-win32)
      shell: cmd
      run: |
        echo ::group:: run build-tcc.bat
        cd win32
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=arm64
        call build-tcc.bat -c cl -t arm64
        @echo off
        echo ::endgroup::
        cd ..\tests
        call test-win32.bat -c clang -t arm64 test -k
